const pages = [
  {id:'aim',label:'Aim'}, {id:'overview',label:'Overview'}, {id:'recap',label:'Recap'}, {id:'pretest',label:'Pretest'},
  {id:'branching',label:'Git Branching',group:true}, {id:'branch-concept',label:'Concept',sub:true}, {id:'branch-demo',label:'Interactive Demo',sub:true},
  {id:'merging',label:'Merging',group:true}, {id:'merge-concept',label:'Concept',sub:true}, {id:'merge-practice',label:'Practice',sub:true},
  {id:'conflicts',label:'Conflict Resolution',group:true}, {id:'conflict-lab',label:'Hands-on Lab',sub:true}, {id:'quiz',label:'Quiz'}, {id:'exercise',label:'Exercise'}
];
const content = document.getElementById('content'), nav = document.getElementById('sideNav');
let state = JSON.parse(localStorage.getItem('gitLabState') || '{"completed":[],"commits":1,"branch":"main","feature":0,"merged":false}');
const save=()=>{localStorage.setItem('gitLabState',JSON.stringify(state)); updateProgress()};
const done=id=>{if(!state.completed.includes(id)) state.completed.push(id);save()};
const toast=msg=>{const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};

function renderNav(){nav.innerHTML=pages.map(p=>`<button data-page="${p.id}" class="${p.sub?'sub ':''}${p.group?'group ':''}">${p.label}</button>`).join('');nav.onclick=e=>{const b=e.target.closest('[data-page]');if(b) go(b.dataset.page)}}
function updateProgress(){const pct=Math.round(state.completed.length/pages.length*100);document.getElementById('progressText').textContent=pct+'%';document.getElementById('progressBar').style.width=pct+'%'}
function shell(title,body){return `<h1 class="page-title">${title}</h1>${body}`}
const aim=()=>shell('Git Branching, Merging and Conflict Resolution',`<p class="lead">Learn to develop features safely in parallel, combine work with confidence, and resolve competing changes without losing code.</p><h2>Aim</h2><p>To understand and practise the Git workflow for creating branches, recording independent changes, merging histories, identifying conflicts, and resolving them correctly.</p><div class="outcomes"><div class="outcome"><h3>Branch</h3><p>Isolate work without disturbing the stable code line.</p></div><div class="outcome"><h3>Merge</h3><p>Integrate completed work and understand merge outcomes.</p></div><div class="outcome"><h3>Resolve</h3><p>Read conflict markers, choose the intended result, and finish safely.</p></div></div><div class="callout"><strong>Estimated time:</strong> 35–45 minutes &nbsp; <span class="tag">Beginner friendly</span></div>`);
const overview=()=>shell('Overview',`<p>Git stores your project as a graph of commits. A branch is a movable label pointing to one commit. This makes experimentation cheap: create a branch, work, and later combine it with another line of development.</p><div class="concept-grid"><div class="concept"><h3>Repository</h3><p>The project database containing commits, references, and history.</p></div><div class="concept"><h3>Commit</h3><p>A saved snapshot with a message, author, timestamp, and parent commit.</p></div><div class="concept"><h3>Branch</h3><p>A named pointer that advances as new commits are created.</p></div><div class="concept"><h3>HEAD</h3><p>The pointer indicating the branch or commit currently checked out.</p></div></div><h2>Experiment flow</h2><ol><li>Check your starting knowledge in the pretest.</li><li>Create a feature branch in the interactive demo.</li><li>Compare fast-forward and three-way merges.</li><li>Resolve a realistic content conflict.</li><li>Complete the quiz and practical exercise.</li></ol>`);
const recap=()=>shell('Prerequisite Recap',`<h2>Before you begin</h2><p>You should know the role of the working directory, staging area, and repository.</p><span class="command">git status</span><p>Shows changed, staged, and untracked files.</p><span class="command">git add README.md</span><p>Stages a selected change for the next commit.</p><span class="command">git commit -m "Document setup"</span><p>Creates a commit from staged changes.</p><div class="callout">A commit records staged content—not every file currently changed on your computer.</div>`);
const quizPage=(pre=false)=>shell(pre?'Pretest':'Quiz',`<div class="quiz-meta"><label><input type="checkbox" checked> Beginner</label><label><input type="checkbox" checked> Intermediate</label></div><form id="quizForm"><div class="question"><p>1. What does a Git branch primarily represent?</p>${opts('q1',['A complete copy of the repository','A movable pointer to a commit','A remote server','A list of untracked files'])}</div><div class="question"><p>2. Which command creates and switches to a new branch?</p>${opts('q2',['git branch --delete feature','git merge feature','git switch -c feature','git status feature'])}</div><div class="question"><p>3. When do conflict markers usually appear?</p>${opts('q3',['When Git cannot automatically combine overlapping changes','After every commit','Only while cloning','Whenever a branch is created'])}</div><div class="question"><p>4. What should happen after resolving all conflict markers?</p>${opts('q4',['Delete the repository','Stage the resolved file and complete the merge','Run git clone','Rename main'])}</div><button class="primary" type="submit">Submit ${pre?'Pretest':'Quiz'}</button><div class="quiz-result" id="quizResult"></div></form>`);
function opts(name,arr){return arr.map((x,i)=>`<label class="option"><input type="radio" name="${name}" value="${i}" required> ${String.fromCharCode(97+i)}: ${x}</label>`).join('')}
const branching=()=>shell('Git Branching',`<h2>Why branches?</h2><p>Branches let developers work on features, experiments, and fixes without destabilising the main line. They are lightweight references—not full directory copies.</p><span class="command">git switch -c feature/login</span><span class="command">git branch --show-current</span><h2>A safe workflow</h2><ol><li>Begin from an updated stable branch.</li><li>Create a clearly named branch.</li><li>Make focused commits with meaningful messages.</li><li>Review the diff and test before merging.</li></ol>`);
const branchDemo=()=>shell('Interactive Branching Demo',`<p>Build a miniature commit graph. Commands update the model entirely in your browser.</p><div class="git-stage"><div class="stage-toolbar"><button data-act="branch">Create feature branch</button><button data-act="commit">Commit change</button><button data-act="switch">Switch branch</button><button data-act="reset">Reset demo</button></div><div class="graph" id="graph"></div><div class="terminal" id="terminal">$ git status\nOn branch ${state.branch}\nworking tree clean</div></div><div class="callout">Try: create a branch → commit twice → switch to main. Notice that the branch pointers identify different histories.</div>`);
const merging=()=>shell('Merging',`<h2>Fast-forward merge</h2><p>If the destination branch has not changed, Git can move its pointer directly to the feature branch tip.</p><span class="command">git switch main<br>git merge feature/navigation</span><h2>Three-way merge</h2><p>If both branches contain new commits, Git finds their common ancestor and creates a new merge commit from both lines.</p><div class="concept-grid"><div class="concept"><h3>Fast-forward</h3><p>Linear history; no merge commit is required.</p></div><div class="concept"><h3>Three-way</h3><p>Diverged history; combines two tips with their shared base.</p></div></div><div class="callout"><strong>Important:</strong> A successful automatic merge means Git combined text mechanically. You must still review and test the result.</div>`);
const mergePractice=()=>shell('Merge Practice',`<p>Use the branch simulator first, then merge the feature work into <code>main</code>.</p><div class="git-stage"><div class="stage-toolbar"><button data-act="prepare">Prepare diverged history</button><button data-act="merge">Run git merge feature</button><button data-act="reset">Reset demo</button></div><div class="graph" id="graph"></div><div class="terminal" id="terminal">$ Choose “Prepare diverged history” to begin.</div></div>`);
const conflicts=()=>shell('Conflict Resolution',`<h2>Why conflicts happen</h2><p>A conflict occurs when Git has multiple plausible results and cannot safely decide which content should survive. It pauses the merge and asks you to make the decision.</p><div class="conflict">&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD<br>Navigation: Home | Experiments | About<br>=======<br>Navigation: Home | Labs | Contact<br>&gt;&gt;&gt;&gt;&gt;&gt;&gt; feature/navigation</div><h2>Resolution process</h2><ol><li>Run <code>git status</code> to identify conflicted files.</li><li>Open each file and understand both changes.</li><li>Edit to the correct final content and remove every marker.</li><li>Stage the resolved file with <code>git add</code>.</li><li>Complete the merge commit and test.</li></ol><span class="command">git diff --check<br>git add index.html<br>git commit</span>`);
const conflictLab=()=>shell('Hands-on Conflict Lab',`<p>Two branches changed the same navigation line. Produce a sensible final version, then validate it.</p><div class="file-editor"><div class="editor-pane"><h3>Conflicted file</h3><div class="conflict">&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD<br>Navigation: Home | Experiments | About<br>=======<br>Navigation: Home | Labs | Contact<br>&gt;&gt;&gt;&gt;&gt;&gt;&gt; feature/navigation</div></div><div class="editor-pane"><h3>Your resolved file</h3><textarea id="resolution" spellcheck="false" placeholder="Write the final navigation line here..."></textarea></div></div><button class="primary" id="validateConflict">Validate resolution</button><div class="quiz-result" id="conflictResult"></div>`);
const exercise=()=>shell('Exercise',`<p>Complete this workflow in any practice repository. Check each step as you finish.</p><div class="checklist" id="checklist"><label><input type="checkbox"> Create a repository and make an initial commit on <code>main</code>.</label><label><input type="checkbox"> Create <code>feature/profile</code> and commit a profile heading.</label><label><input type="checkbox"> Return to <code>main</code> and change the same heading differently.</label><label><input type="checkbox"> Merge <code>feature/profile</code> and inspect the conflict.</label><label><input type="checkbox"> Resolve the content intentionally, stage it, and finish the merge.</label><label><input type="checkbox"> Draw or inspect the history using <code>git log --graph --oneline --all</code>.</label></div><div class="callout"><strong>Expected evidence:</strong> command history, the final resolved file, and a commit graph showing both branches joining.</div>`);

const renderers={aim,overview,recap,pretest:()=>quizPage(true),branching,'branch-concept':branching,'branch-demo':branchDemo,merging,'merge-concept':merging,'merge-practice':mergePractice,conflicts,'conflict-lab':conflictLab,quiz:()=>quizPage(false),exercise};
function go(id){if(!renderers[id]) id='aim';content.innerHTML=renderers[id]();document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id));history.replaceState(null,'','#'+id);document.getElementById('sidebar').classList.remove('open');content.focus();wire(id);if(!['pretest','quiz','conflict-lab','exercise','branch-demo','merge-practice'].includes(id))done(id)}
function graph(){const el=document.getElementById('graph');if(!el)return;let main='<div class="commit-row">';for(let i=0;i<state.commits;i++)main+=`<div class="commit">M${i+1}</div>`;main+=`<span class="branch-label" style="left:${25+(state.commits-1)*100}px;top:0">main</span></div>`;let feature='';if(state.feature){feature='<div class="commit-row">'+Array.from({length:state.feature},(_,i)=>`<div class="commit feature">F${i+1}</div>`).join('')+`<span class="branch-label">feature</span></div>`}el.innerHTML=main+feature}
function wire(id){graph();document.querySelector('.stage-toolbar')?.addEventListener('click',e=>{const a=e.target.dataset.act;if(!a)return;const term=document.getElementById('terminal');if(a==='reset'){state.commits=1;state.feature=0;state.branch='main';state.merged=false;term.textContent='$ Demo reset.'}if(a==='branch'){state.branch='feature';state.feature=Math.max(1,state.feature);term.innerHTML='$ git switch -c feature<br><span class="ok">Switched to a new branch \'feature\'</span>'}if(a==='commit'){if(state.branch==='feature')state.feature++;else state.commits++;term.innerHTML='$ git commit -m "Update project"<br><span class="ok">['+state.branch+'] commit created</span>'}if(a==='switch'){state.branch=state.branch==='main'?'feature':'main';if(state.branch==='feature'&&!state.feature)state.feature=1;term.innerHTML='$ git switch '+state.branch+'<br><span class="ok">Switched to branch \' '+state.branch+' \'</span>'}if(a==='prepare'){state.commits=3;state.feature=2;state.branch='main';state.merged=false;term.textContent='$ History prepared: main and feature have diverged.'}if(a==='merge'){if(!state.feature){term.textContent='$ Nothing to merge. Prepare history first.'}else{state.commits++;state.merged=true;term.innerHTML='$ git merge feature<br><span class="ok">Merge made by the ort strategy.</span>';done(id)}}save();graph()});
  const q=document.getElementById('quizForm');if(q)q.onsubmit=e=>{e.preventDefault();const f=new FormData(q),ans=[1,2,0,1],score=ans.reduce((s,a,i)=>s+(Number(f.get('q'+(i+1)))===a),0),r=document.getElementById('quizResult');r.style.display='block';r.innerHTML=`<strong>Score: ${score}/4</strong><br>${score===4?'Excellent—every answer is correct.':score>=3?'Good work. Review the item you missed and try again.':'Review the concept pages, then retry the quiz.'}`;if(score>=3)done(id)};
  const v=document.getElementById('validateConflict');if(v)v.onclick=()=>{const val=document.getElementById('resolution').value.trim(),r=document.getElementById('conflictResult'),valid=val.includes('Navigation:')&&!/[<=>]{7}/.test(val)&&/Home/i.test(val);r.style.display='block';r.innerHTML=valid?'<strong>Resolution accepted.</strong> Conflict markers are gone and the result preserves a valid navigation line. Remember to stage and commit it.':'<strong>Not resolved yet.</strong> Remove all conflict markers and produce one final navigation line beginning with “Navigation:”.';if(valid)done(id)};
  const c=document.getElementById('checklist');if(c)c.onchange=()=>{const boxes=[...c.querySelectorAll('input')];if(boxes.every(x=>x.checked)){done(id);toast('Exercise complete!')}}}

renderNav();updateProgress();document.getElementById('menuButton').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.getElementById('rateButton').onclick=()=>{document.getElementById('modalContent').innerHTML='<h2>Rate this experiment</h2><p class="stars">★★★★★</p><p>Thank you for helping improve this learning experience.</p>';document.getElementById('modal').showModal()};document.getElementById('bugButton').onclick=()=>{document.getElementById('modalContent').innerHTML='<h2>Report a Bug</h2><p>Describe what happened and include the page name and steps to reproduce.</p><a class="primary" href="https://github.com/saksham-arch/git-branching-virtual-lab/issues/new" target="_blank">Open GitHub issue</a>';document.getElementById('modal').showModal()};document.querySelector('#modal .close').onclick=()=>document.getElementById('modal').close();window.addEventListener('hashchange',()=>go(location.hash.slice(1)));go(location.hash.slice(1)||'aim');
